server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# AUTH ROUTES
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**


# USER ROUTES
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**


# PROFILE IMAGE ROUTES
spring.cloud.gateway.routes[2].id=user-uploads
spring.cloud.gateway.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/uploads/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0


# PLAYLIST ROUTES
spring.cloud.gateway.routes[3].id=playlist-service
spring.cloud.gateway.routes[3].uri=lb://PLAYLIST-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/playlists/**


# SONG ROUTES
spring.cloud.gateway.routes[4].id=song-service
spring.cloud.gateway.routes[4].uri=lb://SONG-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/songs/**


# SONG FILES
spring.cloud.gateway.routes[5].id=song-files
spring.cloud.gateway.routes[5].uri=lb://SONG-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/songs/files/**


# GLOBAL CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true